#!/usr/bin/env node

import fs from "fs";
import path from "path";
import readline from "readline";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

console.log("🏠 Grande Manor Website - Hygraph Setup");
console.log("=====================================\n");

console.log(
  "This script will help you configure your Hygraph CMS connection.\n"
);

console.log("To get your Hygraph credentials:");
console.log("1. Go to https://app.hygraph.com");
console.log("2. Select your project");
console.log("3. Navigate to Project Settings → API Access");
console.log(
  "4. Copy your Content API URL and (optionally) your Permanent Auth Token\n"
);

rl.question("Enter your Hygraph API URL: ", (apiUrl) => {
  if (!apiUrl.trim()) {
    console.log("❌ API URL is required. Exiting...");
    rl.close();
    return;
  }

  rl.question(
    "Enter your API Token (optional, press Enter to skip): ",
    (apiToken) => {
      const envContent = `# Hygraph CMS Configuration
# Generated by setup-hygraph.js

# Your Hygraph API endpoint URL
VITE_HYGRAPH_API_URL=${apiUrl.trim()}

# Your Hygraph API token (optional, only needed for private content)
${
  apiToken.trim()
    ? `VITE_HYGRAPH_API_TOKEN=${apiToken.trim()}`
    : "# VITE_HYGRAPH_API_TOKEN=your-api-token-here"
}

# Instructions:
# 1. Restart your development server after updating this file
# 2. Visit your homepage to see the Hygraph connection test
# 3. Check the Portfolio page to see your projects from Hygraph
`;

      const envPath = path.join(__dirname, ".env");

      try {
        fs.writeFileSync(envPath, envContent);
        console.log("\n✅ .env file created successfully!");
        console.log("\nNext steps:");
        console.log("1. Restart your development server: npm run dev");
        console.log(
          "2. Visit http://localhost:5175 to see the connection test"
        );
        console.log("3. Check the Portfolio page to see your Hygraph projects");
        console.log(
          "\n🎉 Your Grande Manor Website is now connected to Hygraph!"
        );
      } catch (error) {
        console.error("❌ Error creating .env file:", error.message);
      }

      rl.close();
    }
  );
});
